### PR TITLE
added Julia's decision

### PR DESCRIPTION
**Pull request by Gabriel-Bizarria**
Added Julia's decision story

### CODE REVIEW

**Review by ArthurDornelles — APPROVED** [review]
I feel so happy for Julia!

**Review by RaulScapiniWeiand — APPROVED** [review]
Looking Good!

**Review by MelissaZhu01 — APPROVED** [review]
até que está fazendo sentido hahahaha

**Review by MartinbianchoEduardo — APPROVED** [review]
nice work

**Pull request merged**
